--Problem 175: Combine Two Tables
SELECT P.FIRSTNAME, P.LASTNAME, A.CITY, A.STATE
FROM PERSON P
LEFT JOIN ADDRESS A 
ON P.PERSONID = A.PERSONID;

--Problem 181. Employees Earning More Than Their Managers
SELECT E.NAME
AS EMPLOYEE
FROM EMPLOYEE E
JOIN EMPLOYEE M
ON E.MANAGERID = M.ID
WHERE E.SALARY > M.SALARY;

--Problem 182. Duplicate Emails
SELECT EMAIL
FROM PERSON
GROUP BY EMAIL
HAVING COUNT(EMAIL) > 1;

--Problem 183. Customers Who Never Order
SELECT C.NAME AS Customers
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.ID = O.CUSTOMERID
WHERE O.ID IS NULL;

--Problem 196. Delete Duplicate Emails
DELETE P 
FROM PERSON P
JOIN (
    SELECT MIN(ID) AS MIN_ID, EMAIL
    FROM PERSON
    GROUP BY EMAIL
) AS MIN_EMAILS
ON P.EMAIL = MIN_EMAILS.EMAIL
WHERE P.ID > MIN_EMAILS.MIN_ID;

--Problem 197. Rising Temperature
SELECT W1.ID
FROM WEATHER W1
INNER JOIN WEATHER W2
WHERE DATEDIFF(W1.RECORDDATE, W2.RECORDDATE) = 1
AND W1.TEMPERATURE > W2.TEMPERATURE;

--Problem 511. Game Play Analysis I
SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN
FROM ACTIVITY A1
GROUP BY PLAYER_ID;

--Problem 577. Employee Bonus
SELECT E.NAME, B.BONUS
FROM EMPLOYEE E
LEFT JOIN BONUS B
ON E.EMPID = B.EMPID
WHERE B.BONUS < 1000
OR E.EMPID NOT IN (
    SELECT E.EMPID 
    FROM EMPLOYEE E
    INNER JOIN BONUS B
    ON E.EMPID = B.EMPID
);

--Problem 584. Find Customer Referee
SELECT NAME 
FROM CUSTOMER 
WHERE REFEREE_ID NOT IN (
    SELECT REFEREE_ID
    FROM CUSTOMER
    WHERE REFEREE_ID LIKE "2"
) OR REFEREE_ID IS NULL;

--Problem 586. Customer Placing the Largest Number of Orders
SELECT CUSTOMER_NUMBER
FROM ORDERS
GROUP BY CUSTOMER_NUMBER
ORDER BY COUNT(DISTINCT ORDER_NUMBER) DESC
LIMIT 1;

--Problem 595. Big Countries
SELECT W.NAME, W.POPULATION, W.AREA
FROM WORLD W
WHERE W.AREA >= 3000000
OR W.POPULATION >= 25000000;

--Problem 596. Classes More Than 5 Students
SELECT CLASS 
FROM COURSES
GROUP BY CLASS
HAVING COUNT(DISTINCT STUDENT) >= 5;

